# This is the example Deliverfile
# For more information about each property, visit the GitHub documentation: https://github.com/krausefx/deliver
# 
# You can remove those parts you don't need
# 
# A list of available language codes can be found here: https://github.com/krausefx/deliver#available-language-codes
# 
# Everything next to a # is a comment and will be ignored

# hide_transporter_output # remove the '#' in the beginning of the line, to hide the output while uploading

########################################
# App Metadata
########################################

apple_id '956814360'

# This folder has to include one folder for each language
# More information about automatic screenshot upload: 
# https://github.com/KrauseFx/deliver#upload-screenshots-to-itunes-connect
screenshots_path "./screenshots"


app_icon "./AppIcon.png"

title({
  "en-US" => "Your App Name"
})

# changelog({
#   "en-US" => "iPhone 6 (Plus) Support" 
# })

description({
  'en-US' => "one line too?"
})

copyright "123 Felix Krause"

automatic_release true

app_review_information({
  first_name: "dennis",
  last_name: "last",
  phone_number: "123123",
  email_address: "krausefx123123@gmail.com",
  demo_user: "demo user",
  demo_password: "demo pass",
  notes: "such notes
very new line"
})

primary_category "Business"
secondary_category "Books"

ratings_config_path "./ratings.json"

price_tier 5


########################################
# Building and Testing
########################################

# Dynamic generation of the ipa file
# I'm using Shenzhen by Mattt, but you can use any build tool you want
# Remove the whole block if you do not want to upload an ipa file
ipa do
  # Add any code you want, like incrementing the build 
  # number or changing the app identifier

  # Attention: When you return a valid ipa file, this file will get uploaded and released
  # If you only want to upload app metadata, remove the complete ipa block.

  ENV["IPA_OUTPUT_PATH"]
end

beta_ipa do
  ENV["IPA_OUTPUT_PATH"]
end

success do
  system("say 'Successfully submitted a new version.'")
end