# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

fastlane_version "0.12.5"

before_all do
  # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  # ENV['SIGH_TEAM_ID'] = 'Q2CBPJ58CC'

  # sh "./customShellScript.sh"

  increment_build_number

  # cocoapods

  xctool

  # snapshot
end

lane :test_and_snapshot do
  #frameit
end

lane :beta do
  sigh(adhoc: true)

  produce({
    produce_username: 'felix@sunapps.net',
    produce_app_identifier: 'net.sunapps.177',
    produce_app_name: 'felix',
    produce_language: 'German',
    produce_version: '1.0',
    produce_sku: 123,
    produce_team_name: 'sunappsgmbh'
  })

  deliver

  crashlytics({
    crashlytics_path: 'Crashlytics.framework',
    api_token: '5438780b903e1c576849056256e167ab9fb4e..e',
    build_secret: 'd4df5ab4a11359a..b6601ba2485fdd32e47d044fcc2ccb2da25e2944c7e6...',
    ipa_path: 'fastlane.ipa'
  })

  frameit

  deliver(
    skip_deploy: true,
    beta: true
  )
end

lane :deploy do
  sigh
  frameit
  deliver(
    skip_deploy: true
  )
end

# You can define as many lanes as you want

after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end
