# Customise this file, documentation can be found here: 
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

before_all do
  # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  ENV['SIGH_TEAM_ID'] = 'Q2CBPJ58CC'

  # sh "./customShellScript.sh"

  increment_build_number
  
  # cocoapods

  xctool

  snapshot
end

lane :beta do
  sigh :adhoc
  frameit
  deliver :skip_deploy, :beta
end

lane :deploy do
  sigh
  frameit
  deliver :skip_deploy
end

# You can define as many lanes as you want

after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end